[ClassVersion("1.0.0"), FriendlyName("ROADispatcher")]
class VE_ROADispatcher : OMI_BaseResource
{
    [Key, Description("RES ONE Automation database server/instance name")] String DatabaseServer;
    [Key, Description("RES ONE Automatino database name")] String DatabaseName;
    [Required, Description("File path containing the RES ONE Automation MSIs or the literal path to the installer")] String Path;
    [Required, Description("Microsoft SQL username/password to create"), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Install the specified RES ONE Automation agent version")] String Version;
    [Write, Description("Specified path is a literal file reference")] Boolean IsLiteralPath;
    [Write, ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] String Ensure;
    [Read, Description("Windows Installer Product Name")] String ProductName;
};
