[ClassVersion("1.0.0"), FriendlyName("ROABuildingBlock")]
class VE_ROABuildingBlock : OMI_BaseResource
{
    [Key, Description("RES ONE Automation building block file path")] String Path;
    [Write, Description("RES ONE Automation user credential"), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("RES ONE Automation credential is a RES ONE Automation user")] Boolean IsRESONEAutomationCredential;
};
